---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: cluster-autoscaler-provider
  name: cluster-autoscaler-provider
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: cluster-autoscaler-provider
