name: Kustomize

on:
  push:
    branches: [main]
    paths:
      - "kustomization.yaml"
      - "kustomization.yml"
      - "manifests/**"
      - ".github/workflows/kustomize.yml"
  pull_request:
    branches: [main]
    paths:
      - "kustomization.yaml"
      - "kustomization.yml"
      - "manifests/**"
      - ".github/workflows/kustomize.yml"

permissions:
  contents: read

jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: imranismail/setup-kustomize@v2
      - name: Build manifests
        run: kustomize build . >/dev/null
