name: stagex-build

concurrency:
  cancel-in-progress: true
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"

on:
  push:
    tags:
      - "*.*.*"
      - "v*.*.*"
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "cmd/**"
      - "Containerfile"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "cmd/**"
      - "Containerfile"
      - "Makefile"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: cluster-autoscaler-provider
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/cluster-autoscaler-provider
      RELEASE: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Compute image tags
        id: image_tags
        shell: bash
        run: |
          declare -a tags=()

          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            tags+=(latest)
          fi

          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            tags+=("pr-${{ github.event.number }}")
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            tags+=("${GITHUB_REF_NAME}")
          elif [[ "${GITHUB_REF}" != "refs/heads/main" ]]; then
            tags+=("sha-${GITHUB_SHA::12}")
          fi

          printf 'tags=%s\n' "${tags[*]}" >> "${GITHUB_OUTPUT}"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ env.IMAGE_NAME }}
        uses: ./.github/actions/build-oci-package
        with:
          name: ${{ env.IMAGE_NAME }}
          version: ${{ github.ref_type == 'tag' && github.ref_name || 'dev' }}
          disable-artifact: true
          load-docker: true

      - name: Upload to GHCR
        if: ${{ steps.image_tags.outputs.tags != '' }}
        env:
          TAGS: ${{ steps.image_tags.outputs.tags }}
        run: |
          for tag in ${TAGS}; do
            docker tag "tkhq/${IMAGE_NAME}:latest" "${IMAGE_REPO}:${tag}"
          done
          docker image push --all-tags "${IMAGE_REPO}"
